name: selection_group
description: "The focus-aware, plug-and-play selection engine for Flutter TV, Desktop and Mobile."
version: 0.0.10
homepage: https://github.com/MatheusDAVeloso/selection_group
topics:
  - focus
  - selection
  - tv
  - navigation
  - keyboard
  - remote-control

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0